#!/usr/bin/env bash

set -euxo pipefail

#apiHost=http://127.0.0.1:8080
apiHost=https://api.openapi-generator.tech
#apiHost=https://api-latest-master.openapi-generator.tech
genType=client
apiPath=/api/gen/${genType}s
generator=javascript
generatorOptions=generator-options.json
spec=exchangeratesapi.io.yaml

# YAML -> JSON
if [[ $spec == *.yaml ]] || [[ $spec == *.yml ]]; then
  yq . "$spec" > "$spec.json"
  spec=$spec.json
fi

# Generate and download
jq -s '{ options: .[0], spec: .[1] }' "$generatorOptions" "$spec" \
  | curl -sf \
    -X POST \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -d @- \
    "$apiHost$apiPath/$generator" \
  | jq --raw-output '.link' \
  | wget -i- -Ogenerated.zip

# Clean up existing code
rm -rf "$generator-$genType"

# Extract the code
unzip -o generated.zip
