/**
 * Foreign exchange rates API with currency conversion
 * Exchange rates API is a free service for current and historical foreign exchange rates published by the European Central Bank
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Currency.
* @enum {}
* @readonly
*/
export default class Currency {
    
        /**
         * value: "AUD"
         * @const
         */
        "AUD" = "AUD";

    
        /**
         * value: "BGN"
         * @const
         */
        "BGN" = "BGN";

    
        /**
         * value: "BRL"
         * @const
         */
        "BRL" = "BRL";

    
        /**
         * value: "CAD"
         * @const
         */
        "CAD" = "CAD";

    
        /**
         * value: "CHF"
         * @const
         */
        "CHF" = "CHF";

    
        /**
         * value: "CNY"
         * @const
         */
        "CNY" = "CNY";

    
        /**
         * value: "CZK"
         * @const
         */
        "CZK" = "CZK";

    
        /**
         * value: "DKK"
         * @const
         */
        "DKK" = "DKK";

    
        /**
         * value: "EUR"
         * @const
         */
        "EUR" = "EUR";

    
        /**
         * value: "GBP"
         * @const
         */
        "GBP" = "GBP";

    
        /**
         * value: "HKD"
         * @const
         */
        "HKD" = "HKD";

    
        /**
         * value: "HRK"
         * @const
         */
        "HRK" = "HRK";

    
        /**
         * value: "HUF"
         * @const
         */
        "HUF" = "HUF";

    
        /**
         * value: "IDR"
         * @const
         */
        "IDR" = "IDR";

    
        /**
         * value: "ILS"
         * @const
         */
        "ILS" = "ILS";

    
        /**
         * value: "INR"
         * @const
         */
        "INR" = "INR";

    
        /**
         * value: "ISK"
         * @const
         */
        "ISK" = "ISK";

    
        /**
         * value: "JPY"
         * @const
         */
        "JPY" = "JPY";

    
        /**
         * value: "KRW"
         * @const
         */
        "KRW" = "KRW";

    
        /**
         * value: "MXN"
         * @const
         */
        "MXN" = "MXN";

    
        /**
         * value: "MYR"
         * @const
         */
        "MYR" = "MYR";

    
        /**
         * value: "NOK"
         * @const
         */
        "NOK" = "NOK";

    
        /**
         * value: "NZD"
         * @const
         */
        "NZD" = "NZD";

    
        /**
         * value: "PHP"
         * @const
         */
        "PHP" = "PHP";

    
        /**
         * value: "PLN"
         * @const
         */
        "PLN" = "PLN";

    
        /**
         * value: "RON"
         * @const
         */
        "RON" = "RON";

    
        /**
         * value: "RUB"
         * @const
         */
        "RUB" = "RUB";

    
        /**
         * value: "SEK"
         * @const
         */
        "SEK" = "SEK";

    
        /**
         * value: "SGD"
         * @const
         */
        "SGD" = "SGD";

    
        /**
         * value: "THB"
         * @const
         */
        "THB" = "THB";

    
        /**
         * value: "TRY"
         * @const
         */
        "TRY" = "TRY";

    
        /**
         * value: "USD"
         * @const
         */
        "USD" = "USD";

    
        /**
         * value: "ZAR"
         * @const
         */
        "ZAR" = "ZAR";

    

    /**
    * Returns a <code>Currency</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Currency} The enum <code>Currency</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

