/**
 * Foreign exchange rates API with currency conversion
 * Exchange rates API is a free service for current and historical foreign exchange rates published by the European Central Bank
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';

/**
 * The DailyRates model module.
 * @module model/DailyRates
 * @version 1.0.0
 */
class DailyRates {
    /**
     * Constructs a new <code>DailyRates</code>.
     * Rates wrapped with base and date information
     * @alias module:model/DailyRates
     * @param rates {Object.<String, Number>} Currency code / rate pair
     * @param base {module:model/Currency} 
     * @param _date {Date} %Y-%m-%d
     */
    constructor(rates, base, _date) { 
        
        DailyRates.initialize(this, rates, base, _date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rates, base, _date) { 
        obj['rates'] = rates;
        obj['base'] = base;
        obj['date'] = _date;
    }

    /**
     * Constructs a <code>DailyRates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DailyRates} obj Optional instance to populate.
     * @return {module:model/DailyRates} The populated <code>DailyRates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailyRates();

            if (data.hasOwnProperty('rates')) {
                obj['rates'] = ApiClient.convertToType(data['rates'], {'String': 'Number'});
            }
            if (data.hasOwnProperty('base')) {
                obj['base'] = Currency.constructFromObject(data['base']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Currency code / rate pair
 * @member {Object.<String, Number>} rates
 */
DailyRates.prototype['rates'] = undefined;

/**
 * @member {module:model/Currency} base
 */
DailyRates.prototype['base'] = undefined;

/**
 * %Y-%m-%d
 * @member {Date} date
 */
DailyRates.prototype['date'] = undefined;






export default DailyRates;

