/**
 * Foreign exchange rates API with currency conversion
 * Exchange rates API is a free service for current and historical foreign exchange rates published by the European Central Bank
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Exchangeratesapi);
  }
}(this, function(expect, Exchangeratesapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Exchangeratesapi.HistoryRates();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HistoryRates', function() {
    it('should create an instance of HistoryRates', function() {
      // uncomment below and update the code to test HistoryRates
      //var instane = new Exchangeratesapi.HistoryRates();
      //expect(instance).to.be.a(Exchangeratesapi.HistoryRates);
    });

    it('should have the property rates (base name: "rates")', function() {
      // uncomment below and update the code to test the property rates
      //var instane = new Exchangeratesapi.HistoryRates();
      //expect(instance).to.be();
    });

    it('should have the property startAt (base name: "start_at")', function() {
      // uncomment below and update the code to test the property startAt
      //var instane = new Exchangeratesapi.HistoryRates();
      //expect(instance).to.be();
    });

    it('should have the property base (base name: "base")', function() {
      // uncomment below and update the code to test the property base
      //var instane = new Exchangeratesapi.HistoryRates();
      //expect(instance).to.be();
    });

    it('should have the property endAt (base name: "end_at")', function() {
      // uncomment below and update the code to test the property endAt
      //var instane = new Exchangeratesapi.HistoryRates();
      //expect(instance).to.be();
    });

  });

}));
